### ISSUE TITLE
戳一戳发送失败

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-sr-nb#1]

**Comment by SlightDust** [comment]
明白了，sr需要用touch，[CQ:touch,id=1085289815]

**Comment by SlightDust** [comment]
原戳一戳
`poke = MessageSegment(type_='poke',data={'qq': str(ev.user_id),})`

**Comment by SlightDust** [comment]
替换为以下两种方式后，可以发送戳一戳，但代码到这里会抛出异常。
```python
poke = MessageSegment(type_='touch',data={'id': str(ev.user_id),})
poke = f"[CQ:touch,id={ev.user_id}]"
```
```python
[2023-10-15 15:56:41,772 my_chat] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when zaine handling message 1792658311.
[2023-10-15 15:56:41,772 my_chat] ERROR: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 1}>
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/root/qqbot/HoshinoBot/hoshino/modules/my_chat/my_chat.py", line 106, in zaine
    await bot.send(ev, poke)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 1}>
```

**Comment by SlightDust** [comment]
sr已修复https://github.com/linxinrao/Shamrock/actions/runs/6523602905

**Comment by SlightDust** [comment]
替换成了`poke = f"[CQ:touch,id={ev.user_id}]"`
