### ISSUE TITLE
保存表情功能报错

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-sr-nb#3]
```python
[2023-10-15 00:38:32,791 get_sticker] INFO: Message 1432930978 triggered recall.
[2023-10-15 00:38:32,791 get_sticker] ERROR: <class 'IndexError'> occured when recall handling message 1432930978.
[2023-10-15 00:38:32,791 get_sticker] ERROR: list index out of range
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/qqbot/HoshinoBot/hoshino/modules/get_sticker_HoshinoBot/get_sticker.py", line 17, in recall
    mid = re.findall(p1, ev.raw_message)[0]  # 表情包消息id
IndexError: list index out of range
```

**Comment by SlightDust** [comment]
看起来是获取回复消息的messige id有问题

**Comment by SlightDust** [comment]
index out of range还是和 botyubao/bugtracker-nt-cc-yunzai-ws#7 一样的问题，已解决

**Comment by SlightDust** [comment]
然后报
```python
[2023-10-15 00:50:06,247 get_sticker] ERROR: <class 'TypeError'> occured when recall handling message 105821521.
[2023-10-15 00:50:06,247 get_sticker] ERROR: expected string or bytes-like object
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/qqbot/HoshinoBot/hoshino/modules/get_sticker_HoshinoBot/get_sticker.py", line 22, in recall
    url = re.findall(p2,message)[0]
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```

**Comment by SlightDust** [comment]
```python
        msg = await bot.get_msg(message_id = mid)  # 表情包消息HTTP响应
        message = msg['message']  # 表情包消息message对象
        print(message,type(message))
```
这个type，sr会给list形式，按之前的写法，gocq给的是string。  
做一个强制类型转换转成string。

**Comment by SlightDust** [comment]
做一个兼容
```python
        if type(message) == list:  # 收到的是一个消息段
            url = message[0]['data']['url']
            await bot.send(ev,f"[CQ:reply,id={rmid}]{url}")
        elif type(message) == str and "[CQ:image" in message:  # 收到的是一个CQ码
            try:
                p2 = re.compile(r'(https?://.*)\]')
                url = re.findall(p2,message)[0]
                await bot.send(ev,f"[CQ:reply,id={rmid}]{url}")
            except IndexError as e:
                await bot.send(ev, "未匹配到表情")
        else:
            await bot.send(ev, f"message未知消息类型{type(message)}，请反馈")
```

**Comment by SlightDust** [comment]
不过发送的是一个CQ码可能还是隐患，先不管了，能跑就行。
