### ISSUE TITLE
戳一戳集卡不可用

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-sr-nb#5]
Hoshino未收到戳一戳的上报。  
sr报错
```
[00:46:17] WARN java.lang.IllegalStateException: Instance is not ProtoMap
	at moe.fuqiuluo.proto.ProtoValue$DefaultImpls.get(ProtoValue.kt:34)
	at moe.fuqiuluo.proto.ProtoByteString.get(ProtoByteString.kt:9)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.onGroupPoke(PrimitiveListener.kt:76)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.onMsgPush(PrimitiveListener.kt:62)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener.access$onMsgPush(PrimitiveListener.kt:29)
	at moe.fuqiuluo.shamrock.remote.service.listener.PrimitiveListener$registerListener$1$1.invokeSuspend(PrimitiveListener.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at [kotlinx.coroutines.DispatchedTask.run](http://kotlinx.coroutines.dispatchedtask.run/)(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$[Worker.run](http://worker.run/)(CoroutineScheduler.kt:684)
[00:46:17] WARN 不支持的提示类型: GrayTipElement{subElementType=12,revokeElement=null,proclamationElement=null,emojiReplyElement=null,groupElement=null,buddyElement=null,feedMsgElement=null,essenceElement=null,groupNotifyElement=null,buddyNotifyElement=null,xmlElement=XmlElement{busiType=12,busiId=1061,c2cType=0,serviceType=0,ctrlFlag=7,content=<gtip align="center"> <qq uin="u_SxwVMIKiExs16lAPjHq-NQ" col="1" nm="" /> <img src="http://tianquan.gtimg.cn/nudgeaction/item/0/expression.jpg" jp="https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&amp;actionId=0" /> <nor txt="戳了戳"/> <qq uin="u_yorOrPUSz1Ca1jRFeTj0CA" col="1" nm="" tp="0"/> <nor txt=""/> </gtip>,templId=1132,seqId=846271062,templParam={type_str2=0, uin_str1=1085289815, uin_str2=2471737329, jp_str1=https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&amp;actionId=0, action_img_url=http://tianquan.gtimg.cn/nudgeaction/item/0/expression.jpg, action_str=戳了戳, nick_str2=, suffix_str=, nick_str1=},pbReserv=null,members={u_SxwVMIKiExs16lAPjHq-NQ=轻尘喵, u_yorOrPUSz1Ca1jRFeTj0CA=域宝②~NT/Shamrock迁移测试中},},fileReceiptElement=null,localGrayTipElement=null,blockGrayTipElement=null,aioOpGrayTipElement=null,jsonGrayTipElement=null,walletGrayTipElement=null,}
```

**Comment by fuqiuluo** [comment]
问题请移动到Shamrock主项目

**Comment by SlightDust** [comment]
verified in sr [d868932](https://github.com/linxinrao/Shamrock/commit/d868932c2a47530056d5500d0dea54296df38285)
