### ISSUE TITLE
rua发送失败

### ISSUE THREAD

**Issue by SlightDust** [botyubao/bugtracker-sr-nb#6]
```python
/root/qqbot/HoshinoBot/hoshino/modules/shebot/rua/data/output.gif
[2023-10-15 01:13:20,087 Rua] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when creep handling message 104153743.
[2023-10-15 01:13:20,087 Rua] ERROR: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 2}>
Traceback (most recent call last):
  File "/root/qqbot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/root/qqbot/HoshinoBot/hoshino/modules/shebot/rua/__init__.py", line 30, in creep
    await bot.send(ev, R.image(output))
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo={'seq': 2}>
```

**Comment by SlightDust** [comment]
rua模块用file返回了文件，sh日志报No such file or directory，还是存在跨主机的问题，得想办法转移到http
```python
    @classmethod
    def image(cls, pic_path: str) -> 'MessageSegment':
        if cls.check_exist(pic_path):
            return MessageSegment.image(f'file:///{pic_path}')
        elif cls.check_exist(path.join(cls.image_dir, pic_path)):
            return MessageSegment.image(f'file:///{path.join(cls.image_dir, pic_path)}')
        else:
            return '【图片丢了】'
```

**Comment by SlightDust** [comment]
改成base64传值，能正常发送了
```python
    output = generate_gif(data_dir, avatar)
    #print(output)
    #await bot.send(ev, R.image(output))
    with open(output,'rb') as ruagif:
        ruab64=base64.b64encode(ruagif.read()).decode('utf-8')
    await bot.send(ev, f"[CQ:image,file=base64://{ruab64}]")
```
